apiVersion: apps/v1
kind: Deployment
metadata:
  name: myprofile-deployment
spec:
  selector:
    matchLabels:
      app: myprofile-deployment
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myprofile-deployment
    spec:
      containers:
      - name: myprofile-deployment
        image: vindictive/profile-page:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myprofile-deployment-service
spec:
  type: LoadBalancer
  selector: 
    app: myprofile-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
# kubectl apply -f .\kube-deployment-files\myprofile-deployment.yaml
# kubectl get services
# minikube service myprofile-deployment-service for minikube deployment