name: Github Pages Deploy

on:
  push:
      branches:
        - "master"

jobs:
  build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [15.x]

      steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Deploy to gh-pages
          run: npm install && npm run deploy
